"""add leave type entitlement

Revision ID: 16c6d96ddc58
Revises: 665a85e85656
Create Date: 2025-10-21 22:18:30.241585

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16c6d96ddc58'
down_revision = '665a85e85656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leavetype', sa.Column('entitlement', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leavetype', 'entitlement')
    # ### end Alembic commands ###
