"""add team to user

Revision ID: 4ad0e3b90ad0
Revises: 16c6d96ddc58
Create Date: 2025-10-21 23:02:28.438558

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4ad0e3b90ad0'
down_revision = '16c6d96ddc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'team_id')
    # ### end Alembic commands ###
