"""change policy for model

Revision ID: 5625c54dfe67
Revises: a589bd19442a
Create Date: 2025-11-08 14:32:15.696374

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5625c54dfe67'
down_revision = 'a589bd19442a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy', sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('policy', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy', 'score')
    op.drop_column('policy', 'operation')
    # ### end Alembic commands ###
