"""Add column is-allow-plan

Revision ID: 7f4ecea2fb94
Revises: f161caba231f
Create Date: 2025-12-04 07:53:10.523491

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f4ecea2fb94'
down_revision = 'f161caba231f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leavetype', sa.Column('is_allow_plan', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leavetype', 'is_allow_plan')
    # ### end Alembic commands ###
