"""rename approval-at

Revision ID: 8ee030624edd
Revises: 976a05132a16
Create Date: 2025-11-08 16:38:14.343665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ee030624edd'
down_revision = '976a05132a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaveplanrequest', sa.Column('approval_at', sa.DateTime(), nullable=True))
    op.drop_column('leaveplanrequest', 'approved_at')
    op.add_column('leaverequest', sa.Column('approval_at', sa.DateTime(), nullable=True))
    op.drop_column('leaverequest', 'approved_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaverequest', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('leaverequest', 'approval_at')
    op.add_column('leaveplanrequest', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('leaveplanrequest', 'approval_at')
    # ### end Alembic commands ###
