"""add submitted-datetime to request models

Revision ID: 976a05132a16
Revises: c15bf45299ba
Create Date: 2025-11-08 16:18:02.760283

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '976a05132a16'
down_revision = 'c15bf45299ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaveplanrequest', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('leaverequest', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaverequest', 'submitted_at')
    op.drop_column('leaveplanrequest', 'submitted_at')
    # ### end Alembic commands ###
