"""Add owner-id config-models

Revision ID: 9ce6e1057327
Revises: 2988ab38f742
Create Date: 2025-10-05 16:06:06.188400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ce6e1057327'
down_revision = '2988ab38f742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leavetype', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'leavetype', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('policy', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'policy', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('publicholiday', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'publicholiday', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publicholiday', type_='foreignkey')
    op.drop_column('publicholiday', 'owner_id')
    op.drop_constraint(None, 'policy', type_='foreignkey')
    op.drop_column('policy', 'owner_id')
    op.drop_constraint(None, 'leavetype', type_='foreignkey')
    op.drop_column('leavetype', 'owner_id')
    # ### end Alembic commands ###
