"""add year to request models

Revision ID: c15bf45299ba
Revises: 5625c54dfe67
Create Date: 2025-11-08 15:24:28.299820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c15bf45299ba'
down_revision = '5625c54dfe67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaveplanrequest', sa.Column('year', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True))
    op.add_column('leaverequest', sa.Column('year', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaverequest', 'year')
    op.drop_column('leaveplanrequest', 'year')
    # ### end Alembic commands ###
