"""add model leave balance

Revision ID: c3cc988f8049
Revises: 97818f5e5531
Create Date: 2025-10-08 23:49:46.030949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3cc988f8049'
down_revision = '97818f5e5531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leavebalance',
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leavetype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leavebalance')
    # ### end Alembic commands ###
