"""add username and phone_number to user

Revision ID: e91b6a2d5f3c
Revises: b7f3a9d21c44
Create Date: 2026-07-14 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e91b6a2d5f3c'
down_revision = 'b7f3a9d21c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
    )
    op.add_column(
        'user',
        sa.Column(
            'phone_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
