"""add taken balance fields

Revision ID: f161caba231f
Revises: 8ee030624edd
Create Date: 2025-11-19 22:38:06.928334

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f161caba231f'
down_revision = '8ee030624edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leavebalance', sa.Column('taken_balance', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leavebalance', 'taken_balance')
    # ### end Alembic commands ###
