"""remove unique

Revision ID: fed78d1aa6e9
Revises: c3cc988f8049
Create Date: 2025-10-10 22:29:59.654290

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fed78d1aa6e9'
down_revision = 'c3cc988f8049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leavetype_code'), table_name='leavetype')
    op.create_index(op.f('ix_leavetype_code'), 'leavetype', ['code'], unique=False)
    op.drop_index(op.f('ix_policy_code'), table_name='policy')
    op.create_index(op.f('ix_policy_code'), 'policy', ['code'], unique=False)
    op.drop_index(op.f('ix_publicholiday_date'), table_name='publicholiday')
    op.create_index(op.f('ix_publicholiday_date'), 'publicholiday', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicholiday_date'), table_name='publicholiday')
    op.create_index(op.f('ix_publicholiday_date'), 'publicholiday', ['date'], unique=True)
    op.drop_index(op.f('ix_policy_code'), table_name='policy')
    op.create_index(op.f('ix_policy_code'), 'policy', ['code'], unique=True)
    op.drop_index(op.f('ix_leavetype_code'), table_name='leavetype')
    op.create_index(op.f('ix_leavetype_code'), 'leavetype', ['code'], unique=True)
    # ### end Alembic commands ###
